import type { RadarCompany } from "./types";

export const RADAR_COMPANIES: RadarCompany[] = [
  { name: "Nazaríes IT",          careers_url: "https://nazaries.com/trabaja-con-nosotros/" },
  { name: "JTSEC",                careers_url: "https://www.jtsec.es/empleo" },
  { name: "Innovasur",            careers_url: "https://innovasur.es/trabaja-con-nosotros/" },
  { name: "Atlax360",             careers_url: "https://atlax360.com/empleo/" },
  { name: "IAGT",                 careers_url: "https://iagt.es/empleo/" },
  { name: "SmallDev",             careers_url: "https://smalldev.es/jobs/" },
  { name: "FIDESOL",              careers_url: "https://fidesol.org/empleo/" },
  { name: "Camarero10",           careers_url: "https://camarero10.com/trabaja-con-nosotros/" },
  { name: "Galdón Software",      careers_url: "https://www.galdon.com/empleo/" },
  { name: "Solinsur",             careers_url: "https://solinsur.com/empleo/" },
  { name: "Firmafy",              careers_url: "https://firmafy.com/equipo/" },
  { name: "Q2B Studio",           careers_url: "https://q2bstudio.com/empleo/" },
  { name: "ATISoluciones",        careers_url: "https://atisoluciones.com/trabaja-con-nosotros/" },
  { name: "Trevenque",            careers_url: "https://trevenque.es/empleo/" },
  { name: "SIDN Digital Thinking",careers_url: "https://sidn.es/trabaja-con-nosotros/" },
  { name: "Nucleoo",              careers_url: "https://nucleoo.com/careers/" },
  { name: "Kyndryl Granada",      careers_url: "https://www.kyndryl.com/es/es/careers" },
  { name: "Cívica Software",      careers_url: "https://www.civica.com/en-gb/careers/" },
  { name: "Experian Granada",     careers_url: "https://www.experianplc.com/careers" },
  { name: "HTEC Group",           careers_url: "https://htecgroup.com/careers/" },
  { name: "Ayesa",                careers_url: "https://www.ayesa.com/empleo/" },
  { name: "Inetum",               careers_url: "https://www.inetum.com/es/careers" },
  { name: "NTT DATA Spain",       careers_url: "https://es.nttdata.com/empleo" },
  { name: "Minsait Granada",      careers_url: "https://www.minsait.com/es/sobre-nosotros/trabaja-con-nosotros" },
  { name: "Breca Health Care",    careers_url: "https://brecahealthcare.com/trabaja-con-nosotros/" },
];
