/**
 * Source registry — Noticias / Radar diario.
 *
 * Categorías activas:
 *   granada          → Economía y noticias locales de Granada
 *   ia               → Inteligencia Artificial (global + hub IA Granada)
 *   empresas_granada → Empresas tech y noticias empresariales en Granada
 *   eventos_granada  → Eventos, charlas y meetups de desarrollo en Granada
 */

export type NewsCategory =
  | "granada"
  | "ia"
  | "empresas_granada"
  | "eventos_granada";

export type SourceMethod =
  | "rss"
  | "rss-list"
  | "api"
  | "html"
  | "html-or-feed-check"
  | "html-link-only"
  | "rss-or-html"
  | "web-link";

export type SourcePriority = "high" | "medium" | "low";

export type Source = {
  id: string;
  name: string;
  category: NewsCategory;
  method: SourceMethod;
  url: string;
  priority: SourcePriority;
  notes?: string;
  tags?: string[];
  feeds?: string[];
};

export const SOURCES: Source[] = [

  // ─── Granada: economía y noticias locales ────────────────────────────────
  {
    id: "ideal-granada",
    name: "Ideal · Granada",
    category: "granada",
    method: "rss",
    url: "https://www.ideal.es/granada/",
    priority: "high",
    feeds: ["https://www.ideal.es/rss/2.0/"],
  },
  {
    id: "ideal-economia",
    name: "Ideal · Economía",
    category: "granada",
    method: "rss",
    url: "https://www.ideal.es/economia/",
    priority: "high",
    feeds: ["https://www.ideal.es/rss/2.0/?section=economia"],
  },
  {
    id: "granada-hoy-granada",
    name: "Granada Hoy",
    category: "granada",
    method: "rss",
    url: "https://www.granadahoy.com/granada/",
    priority: "high",
    feeds: ["https://www.granadahoy.com/granada.rss"],
  },
  {
    id: "granada-hoy-economia",
    name: "Granada Hoy · Economía",
    category: "granada",
    method: "rss",
    url: "https://www.granadahoy.com/economia/",
    priority: "medium",
    feeds: ["https://www.granadahoy.com/economia.rss"],
  },
  {
    id: "granada-digital",
    name: "Granada Digital",
    category: "granada",
    method: "rss",
    url: "https://www.granadadigital.es/",
    priority: "medium",
    feeds: ["https://www.granadadigital.es/feed/"],
  },
  {
    id: "ugr-rss",
    name: "UGR Noticias",
    category: "granada",
    method: "rss",
    url: "https://www.ugr.es/",
    priority: "medium",
    feeds: ["https://www.ugr.es/rss.xml"],
  },
  {
    id: "ahora-granada",
    name: "Ahora Granada",
    category: "granada",
    method: "web-link",
    url: "https://www.ahoragranada.com/",
    priority: "medium",
  },
  {
    id: "europa-press-granada",
    name: "Europa Press · Granada",
    category: "granada",
    method: "web-link",
    url: "https://www.europapress.es/andalucia/granada-00353/",
    priority: "medium",
  },
  {
    id: "noticias101-granada",
    name: "Noticias 101 · Granada",
    category: "granada",
    method: "web-link",
    url: "https://www.101tv.es/granada/",
    priority: "medium",
    notes: "Canal local de Granada, sin RSS confirmado.",
  },

  // ─── IA: Inteligencia Artificial + hub de IA Granada ─────────────────────
  {
    id: "mit-tech-review",
    name: "MIT Technology Review",
    category: "ia",
    method: "rss",
    url: "https://www.technologyreview.com/",
    priority: "high",
    feeds: ["https://www.technologyreview.com/feed/"],
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind Blog",
    category: "ia",
    method: "rss",
    url: "https://deepmind.google/blog/",
    priority: "high",
    feeds: ["https://deepmind.google/blog/rss.xml"],
  },
  {
    id: "hugging-face-blog",
    name: "Hugging Face Blog",
    category: "ia",
    method: "rss",
    url: "https://huggingface.co/blog",
    priority: "high",
    feeds: ["https://huggingface.co/blog/feed.xml"],
  },
  {
    id: "the-batch",
    name: "The Batch · deeplearning.ai",
    category: "ia",
    method: "rss",
    url: "https://www.deeplearning.ai/the-batch/",
    priority: "medium",
    feeds: ["https://www.deeplearning.ai/the-batch/feed/rss.xml"],
  },
  {
    id: "granada-hoy-tecnologia",
    name: "Granada Hoy · Tecnología",
    category: "ia",
    method: "rss",
    url: "https://www.granadahoy.com/tecnologia/",
    priority: "medium",
    feeds: ["https://www.granadahoy.com/tecnologia.rss"],
  },
  {
    id: "cenia-ugr",
    name: "CENIA · UGR (Hub IA Granada)",
    category: "ia",
    method: "web-link",
    url: "https://cenia.ugr.es/",
    priority: "high",
    notes: "Centro de Excelencia en IA de la UGR. Sin RSS confirmado.",
  },
  {
    id: "ideal-tecnologia",
    name: "Ideal · Tecnología",
    category: "ia",
    method: "web-link",
    url: "https://www.ideal.es/tecnologia/",
    priority: "medium",
    notes: "Sección tecnología de Ideal. RSS general ya incluido.",
  },

  // ─── Empresas Granada: noticias y alianzas tech ───────────────────────────

  // — Blogs RSS confirmados ——————————————————————————————————————————————————
  {
    id: "trevenque-blog",
    name: "Trevenque Group · Blog",
    category: "empresas_granada",
    method: "rss",
    url: "https://www.trevenque.es/blog/",
    priority: "high",
    feeds: ["https://www.trevenque.es/blog/feed/"],
  },
  {
    id: "sidn-blog",
    name: "SIDN Digital Thinking · Blog",
    category: "empresas_granada",
    method: "rss",
    url: "https://www.sidn.es/blog/",
    priority: "high",
    feeds: ["https://www.sidn.es/blog/feed/"],
  },
  {
    id: "junta-andalucia-empresa",
    name: "Junta Andalucía · Empresa y Emprendimiento",
    category: "empresas_granada",
    method: "rss",
    url: "https://www.juntadeandalucia.es/economiayhacienda/",
    priority: "medium",
    feeds: ["https://www.juntadeandalucia.es/economiayhacienda/rss.xml"],
    notes: "Noticias de economía y empresa de Andalucía.",
  },
  {
    id: "andalucia-economica",
    name: "Andalucía Económica",
    category: "empresas_granada",
    method: "rss",
    url: "https://www.andaluciaeconomica.com/",
    priority: "medium",
    feeds: ["https://www.andaluciaeconomica.com/feed/"],
    notes: "Revista de economía y empresa andaluza.",
  },

  // — Empresas Granada con blogs (intentar RSS) ——————————————————————————————
  {
    id: "nazaries-blog",
    name: "Nazaríes Intelligenia · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.nazaries.com/es/blog",
    priority: "high",
    feeds: ["https://www.nazaries.com/feed/", "https://www.nazaries.com/blog/feed/"],
  },
  {
    id: "jtsec-blog",
    name: "JTSEC · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://jtsec.es/blog",
    priority: "high",
    feeds: ["https://jtsec.es/feed/", "https://jtsec.es/blog/feed/"],
  },
  {
    id: "innovasur-blog",
    name: "Innovasur · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.innovasur.com/blog",
    priority: "high",
    feeds: ["https://www.innovasur.com/feed/", "https://www.innovasur.com/blog/feed/"],
  },
  {
    id: "atlax360-blog",
    name: "Atlax 360 · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://atlax360.com/blog",
    priority: "high",
    feeds: ["https://atlax360.com/feed/", "https://atlax360.com/blog/feed/"],
  },
  {
    id: "iagt-blog",
    name: "IAGT · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.iagt.es/blog",
    priority: "medium",
    feeds: ["https://www.iagt.es/feed/", "https://www.iagt.es/blog/feed/"],
  },
  {
    id: "smalldev-blog",
    name: "SmallDev · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://smalldev.es/blog",
    priority: "medium",
    feeds: ["https://smalldev.es/feed/", "https://smalldev.es/blog/feed/"],
  },
  {
    id: "fidesol-blog",
    name: "FIDESOL · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://fidesol.org/blog",
    priority: "medium",
    feeds: ["https://fidesol.org/feed/", "https://fidesol.org/blog/feed/"],
  },
  {
    id: "camarero10-blog",
    name: "Camarero10 · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.camarero10.com/blog",
    priority: "medium",
    feeds: ["https://www.camarero10.com/feed/", "https://www.camarero10.com/blog/feed/"],
  },
  {
    id: "galdon-blog",
    name: "Galdón Software · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.galdon.com/blog",
    priority: "medium",
    feeds: ["https://www.galdon.com/feed/", "https://www.galdon.com/blog/feed/"],
  },
  {
    id: "solinsur-blog",
    name: "Solinsur · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.solinsur.net/blog",
    priority: "medium",
    feeds: ["https://www.solinsur.net/feed/", "https://www.solinsur.net/blog/feed/"],
  },
  {
    id: "firmafy-blog",
    name: "Firmafy · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://firmafy.com/blog",
    priority: "medium",
    feeds: ["https://firmafy.com/feed/", "https://firmafy.com/blog/feed/"],
  },
  {
    id: "q2bstudio-blog",
    name: "Q2B Studio · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.q2bstudio.com/nuestro-blog",
    priority: "medium",
    feeds: ["https://www.q2bstudio.com/feed/", "https://www.q2bstudio.com/blog/feed/"],
  },
  {
    id: "atisoluciones-blog",
    name: "ATISoluciones · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.atisoluciones.com/blog",
    priority: "medium",
    feeds: ["https://www.atisoluciones.com/feed/", "https://www.atisoluciones.com/blog/feed/"],
  },
  {
    id: "htec-blog",
    name: "HTEC Group · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://htec.com/insights",
    priority: "medium",
    feeds: ["https://htec.com/feed/", "https://htec.com/blog/feed/"],
  },
  {
    id: "ayesa-blog",
    name: "Ayesa · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.ayesa.com/blog",
    priority: "medium",
    feeds: ["https://www.ayesa.com/feed/", "https://www.ayesa.com/blog/feed/"],
  },
  {
    id: "inetum-blog",
    name: "Inetum · Blog",
    category: "empresas_granada",
    method: "rss-or-html",
    url: "https://www.inetum.com/es/insights",
    priority: "medium",
    feeds: ["https://www.inetum.com/feed/", "https://www.inetum.com/es/feed/"],
  },

  // — Grandes empresas con presencia en Granada (web-link) ——————————————————
  {
    id: "civica-web",
    name: "Cívica Software",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.civica-soft.com/",
    priority: "high",
  },
  {
    id: "nucleoo-web",
    name: "Nucleoo",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.nucleoo.com/",
    priority: "high",
  },
  {
    id: "kyndryl-granada-web",
    name: "Kyndryl · Granada",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.kyndryl.com/es/es/about-us/news",
    priority: "medium",
  },
  {
    id: "nttdata-web",
    name: "NTT DATA Europe & Latam",
    category: "empresas_granada",
    method: "web-link",
    url: "https://es.nttdata.com/",
    priority: "medium",
  },
  {
    id: "minsait-web",
    name: "Minsait / Indra",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.minsait.com/es",
    priority: "medium",
  },
  {
    id: "sdworx-web",
    name: "SD Worx · Granada",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.sdworx.com/",
    priority: "medium",
  },
  {
    id: "strada-web",
    name: "Strada / Alight · Granada",
    category: "empresas_granada",
    method: "web-link",
    url: "https://stradaglobal.com/",
    priority: "medium",
  },
  {
    id: "tsystems-web",
    name: "T-Systems Iberia",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.t-systems.com/es/es",
    priority: "medium",
  },
  {
    id: "telefonica-tech-web",
    name: "Telefónica Tech",
    category: "empresas_granada",
    method: "web-link",
    url: "https://telefonicatech.com/",
    priority: "medium",
  },
  {
    id: "unit4-web",
    name: "Unit4",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.unit4.com/",
    priority: "medium",
  },
  {
    id: "zalaris-web",
    name: "Zalaris · Granada",
    category: "empresas_granada",
    method: "web-link",
    url: "https://zalaris.com/",
    priority: "medium",
  },
  {
    id: "elca-web",
    name: "ELCA Spain",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.elca.ch/",
    priority: "medium",
  },
  {
    id: "kohyoung-web",
    name: "Koh Young Research Spain",
    category: "empresas_granada",
    method: "web-link",
    url: "https://kohyoung.com/",
    priority: "medium",
  },
  {
    id: "safran-seven-solutions-web",
    name: "Safran / Seven Solutions · Granada",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.safran-group.com/",
    priority: "medium",
  },

  // — Ecosistema CT Granada (empresas asociadas) ————————————————————————————
  {
    id: "ansotec-web",
    name: "Ansotec",
    category: "empresas_granada",
    method: "web-link",
    url: "https://ansotec.com/",
    priority: "low",
  },
  {
    id: "arvision-web",
    name: "AR Vision",
    category: "empresas_granada",
    method: "web-link",
    url: "https://arvision.es/",
    priority: "low",
  },
  {
    id: "aumentur-web",
    name: "Aumentur",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.aumentur.app/",
    priority: "low",
  },
  {
    id: "besttic-web",
    name: "BEST TIC",
    category: "empresas_granada",
    method: "web-link",
    url: "https://best-tic.com/",
    priority: "low",
  },
  {
    id: "bios-ts-web",
    name: "BIOS Technology Solutions",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.bios-ts.es/",
    priority: "low",
  },
  {
    id: "breca-web",
    name: "Breca Health Care",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.brecahealthcare.com/",
    priority: "low",
  },
  {
    id: "centromipc-web",
    name: "CentroMIPC",
    category: "empresas_granada",
    method: "web-link",
    url: "https://centromipc.com/",
    priority: "low",
  },
  {
    id: "climbea-web",
    name: "Climbea",
    category: "empresas_granada",
    method: "web-link",
    url: "https://climbea.com/",
    priority: "low",
  },
  {
    id: "closemarketing-web",
    name: "CloseMarketing",
    category: "empresas_granada",
    method: "web-link",
    url: "https://close.marketing/",
    priority: "low",
  },
  {
    id: "coab-web",
    name: "COAB Soluciones",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.coabsoluciones.com/",
    priority: "low",
  },
  {
    id: "debos-web",
    name: "Debos",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.debos.ai/",
    priority: "low",
  },
  {
    id: "desarrolloonline-web",
    name: "Desarrollo Online",
    category: "empresas_granada",
    method: "web-link",
    url: "https://desarrolloonline.com/",
    priority: "low",
  },
  {
    id: "ditratec-web",
    name: "Ditratec",
    category: "empresas_granada",
    method: "web-link",
    url: "https://ditratec.com/",
    priority: "low",
  },
  {
    id: "dtisa-web",
    name: "DTISA",
    category: "empresas_granada",
    method: "web-link",
    url: "https://dtisa.com/",
    priority: "low",
  },
  {
    id: "esistemas-web",
    name: "E-SISTEMAS.NET",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.e-sistemas.net/",
    priority: "low",
  },
  {
    id: "ecope-web",
    name: "ECOPE",
    category: "empresas_granada",
    method: "web-link",
    url: "https://ecope.es/",
    priority: "low",
  },
  {
    id: "emarintel-web",
    name: "Emarintel",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.emarintel.com/",
    priority: "low",
  },
  {
    id: "esail-web",
    name: "Esail",
    category: "empresas_granada",
    method: "web-link",
    url: "https://esail.es/",
    priority: "low",
  },
  {
    id: "facturatech-web",
    name: "FacturaTech",
    category: "empresas_granada",
    method: "web-link",
    url: "https://facturatech.es/",
    priority: "low",
  },
  {
    id: "icr-web",
    name: "ICR",
    category: "empresas_granada",
    method: "web-link",
    url: "https://icr-sa.com/",
    priority: "low",
  },
  {
    id: "idento-web",
    name: "Idento Marketing y Desarrollo",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.idento.es/",
    priority: "low",
  },
  {
    id: "iagrofactory-web",
    name: "iAgro Factory",
    category: "empresas_granada",
    method: "web-link",
    url: "https://iagrofactory.es/",
    priority: "low",
  },
  {
    id: "inforcloud-web",
    name: "Inforcloud",
    category: "empresas_granada",
    method: "web-link",
    url: "https://inforcloud.es/",
    priority: "low",
  },
  {
    id: "inputforyou-web",
    name: "InputForYou",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.inputforyou.be/",
    priority: "low",
  },
  {
    id: "isbue-web",
    name: "Isbue",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.isbue.io/",
    priority: "low",
  },
  {
    id: "nanobytes-web",
    name: "Nanobytes",
    category: "empresas_granada",
    method: "web-link",
    url: "https://nanobytes.es/",
    priority: "low",
  },
  {
    id: "nter-web",
    name: "Nter",
    category: "empresas_granada",
    method: "web-link",
    url: "https://nter.es/",
    priority: "low",
  },
  {
    id: "nubexo-web",
    name: "Nubexo",
    category: "empresas_granada",
    method: "web-link",
    url: "https://nubexo.com/",
    priority: "low",
  },
  {
    id: "rodich-web",
    name: "Rodich Systems",
    category: "empresas_granada",
    method: "web-link",
    url: "https://rodichsys.com/",
    priority: "low",
  },
  {
    id: "sariba-web",
    name: "Sariba",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.sariba.com/",
    priority: "low",
  },
  {
    id: "segurostech-web",
    name: "Seguros.Tech / HispaColex",
    category: "empresas_granada",
    method: "web-link",
    url: "https://seguros.tech/",
    priority: "low",
  },
  {
    id: "sensactive-web",
    name: "Sensactive Tech",
    category: "empresas_granada",
    method: "web-link",
    url: "https://sensactivetech.com/",
    priority: "low",
  },
  {
    id: "tmdigital-web",
    name: "TM Digital Granada",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.tmdigitalgranada.es/",
    priority: "low",
  },
  {
    id: "tdconsulting-web",
    name: "Top Digital / TD Consulting",
    category: "empresas_granada",
    method: "web-link",
    url: "https://tdconsulting.es/",
    priority: "low",
  },
  {
    id: "turningtables-web",
    name: "Turning Tables",
    category: "empresas_granada",
    method: "web-link",
    url: "https://www.turningtables.global/",
    priority: "low",
  },
  {
    id: "wiber-web",
    name: "Wiber",
    category: "empresas_granada",
    method: "web-link",
    url: "https://wiber.es/",
    priority: "low",
  },
  {
    id: "witcreativo-web",
    name: "Wit Creativo",
    category: "empresas_granada",
    method: "web-link",
    url: "https://witcreativo.es/",
    priority: "low",
  },

  // ─── Eventos Granada: charlas, meetups y eventos de desarrollo ────────────
  {
    id: "ugr-eventos",
    name: "UGR · Eventos y Jornadas",
    category: "eventos_granada",
    method: "rss",
    url: "https://eventos.ugr.es/",
    priority: "high",
    feeds: ["https://eventos.ugr.es/api/feed/rss/"],
    notes: "Jornadas académicas y tech de la UGR.",
  },
  {
    id: "andalucia-emprende-granada",
    name: "Andalucía Emprende · Granada",
    category: "eventos_granada",
    method: "web-link",
    url: "https://www.andaluciaemprende.es/provincia/granada/",
    priority: "medium",
  },
  {
    id: "ideas-factory-ugr",
    name: "Ideas Factory UGR",
    category: "eventos_granada",
    method: "web-link",
    url: "https://ideasfactory.es/ugr/",
    priority: "high",
    notes: "Hub de emprendimiento y eventos tech de la UGR.",
  },
  {
    id: "betabeers-granada",
    name: "Betabeers · Granada",
    category: "eventos_granada",
    method: "web-link",
    url: "https://betabeers.com/community/betabeers-granada/",
    priority: "high",
    notes: "Meetup mensual de tech en Granada.",
  },
  {
    id: "gdg-granada",
    name: "GDG · Granada",
    category: "eventos_granada",
    method: "web-link",
    url: "https://gdg.community/gdg/granada/",
    priority: "high",
    notes: "Google Developer Group Granada.",
  },
  {
    id: "eventbrite-granada-tech",
    name: "Eventbrite · Tech Granada",
    category: "eventos_granada",
    method: "web-link",
    url: "https://www.eventbrite.es/d/spain--granada/tech/",
    priority: "medium",
    notes: "Eventos tech en Eventbrite filtrados por Granada.",
  },
];

export const CATEGORY_LABELS: Record<NewsCategory, string> = {
  granada: "Granada",
  ia: "IA",
  empresas_granada: "Empresas",
  eventos_granada: "Eventos",
};

export const CATEGORY_COLORS: Record<NewsCategory, string> = {
  granada: "bg-amber-500/10 text-amber-700 dark:text-amber-300",
  ia: "bg-violet-500/10 text-violet-700 dark:text-violet-300",
  empresas_granada: "bg-blue-500/10 text-blue-700 dark:text-blue-300",
  eventos_granada: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
};

export function getSource(id: string): Source | undefined {
  return SOURCES.find((s) => s.id === id);
}

export function getFetchableSources(): Source[] {
  return SOURCES.filter((s) => s.method !== "web-link" && s.method !== "html-link-only");
}

export function getWebLinkSources(): Source[] {
  return SOURCES.filter((s) => s.method === "web-link" || s.method === "html-link-only");
}
